### ISSUE TITLE
怎么设置sqlite呢

### ISSUE THREAD

**Issue by kinsung** [Meowv/Blog#11]
这是一个很好的blog和笔记软件，请教怎么设置和支持sqlite呢？怎么增加一个搜索功能？

**Comment by Meowv** [comment]
支持的，配置文件里面可以改需要用什么数据库，和连接字符串就行。搜索功能可以自己加一个接口就可以了，我这里用不到就没做。

后续会写一个配置说明的。

**Comment by kinsung** [comment]
使用sqlite报错。

**Comment by Meowv** [comment]
[blog_tutorial](https://github.com/Meowv/Blog/tree/blog_tutorial)  分支代码我试了下，可以的已经做了适配，代码已传。

主要需要修改以下几个地方：

1. `Meowv.Blog.HttpApi.Hosting` 下 `appsettings.json`连接字符串和`Enable`启用Sqlite。
2. `Meowv.Blog.EntityFrameworkCore` 下 `MeowvBlogDbContext` 需要修改 `ConnectionStringName` Attribute 为Sqlite。
3. `Meowv.Blog.BackgroundJobs` 也对应的需要修改支持Sqlite。默认只支持 Mysql，如果不需要，可以在`MeowvBlogHttpApiHostingModule`模块中取消依赖。如果需要`Hangfire`功能，你看一下代码。

```csharp
context.Services.AddHangfire(config =>
            {
                if (AppSettings.EnableDb == "MySQL")
                {
                    config.UseStorage(
                        new MySqlStorage(AppSettings.ConnectionStrings,
                        new MySqlStorageOptions
                        {
                            TablePrefix = MeowvBlogConsts.DbTablePrefix + "hangfire"
                        }));

                }
                else if (AppSettings.EnableDb == "Sqlite")
                {
                    config.UseSQLiteStorage(AppSettings.ConnectionStrings, new SQLiteStorageOptions
                    {
                        SchemaName = MeowvBlogConsts.DbTablePrefix + "hangfire"
                    });
                }
            });
```

4. 如果你要用EF Code-First功能，对应的`Meowv.Blog.EntityFrameworkCore.DbMigrations` 也修改一下连接字符串，和 `MeowvBlogMigrationsDbContextFactory` 改一下`UseSqlite`即可。


还有报错很正常，自己尝试解决。你报错总得告诉我报错的原因，和报的什么错，不然我怎么去定位问题？ 谢谢支持。
