### ISSUE TITLE
你好，阿星

### ISSUE THREAD

**Issue by tonfy** [Meowv/Blog#13]
你的接口和WEB分开部署不会有跨域问题吗，我的新增可以，删除会有跨域问题

**Comment by Meowv** [comment]
我两种解决方式：
1. 代码中设置允许跨域：https://github.com/Meowv/Blog/blob/master/src/Meowv.Blog.HttpApi.Hosting/MeowvBlogHttpApiHostingModule.cs
2. 我部署在Linux下，用Nginx做的转发，所以可以设置请求头`add_header Access-Control-Allow-Origin *;`
