### ISSUE TITLE
找不到默认构造器

### ISSUE THREAD

**Issue by yhxwyzm** [Meowv/Blog#15]
你好，我在学习你的这个abp系列的时候遇到了一个问题
在 《基于 abp vNext 和 .NET Core 开发博客项目 - 自定义仓储之增删改查》 这篇文章中我按照你的代码操作了之后代码跑起来后swagger报500的错误

具体内容如下图
![image](https://user-images.githubusercontent.com/37857613/89628598-1c215d80-d8cf-11ea-8ef3-09e18d9e317e.png)

![image](https://user-images.githubusercontent.com/37857613/89628666-39562c00-d8cf-11ea-995e-13f6604a71ae.png)

![image](https://user-images.githubusercontent.com/37857613/89628687-3f4c0d00-d8cf-11ea-9cd4-c1aaa3e36669.png)

![image](https://user-images.githubusercontent.com/37857613/89628702-4541ee00-d8cf-11ea-877e-96b1b6a98e59.png)

![image](https://user-images.githubusercontent.com/37857613/89628717-4b37cf00-d8cf-11ea-8c5f-54b231b8841f.png)

![image](https://user-images.githubusercontent.com/37857613/89628729-512db000-d8cf-11ea-8bf0-5d0787e709f1.png)

.net core 3.1
mysql

**Comment by Meowv** [comment]
根据报错堆栈来看，你检查一下模块之间的依赖，一般调试一下就知道哪里出问题了。

**Comment by yhxwyzm** [comment]
> 根据报错堆栈来看，你检查一下模块之间的依赖，一般调试一下就知道哪里出问题了。

我检查了一下依赖和你的代码保持一致了，但是他还是会这样报错，断点都不进的

**Comment by Meowv** [comment]
可以将代码上传 github 或者 打包发给我，我晚上有空帮你看看

**Comment by yhxwyzm** [comment]
https://wws.lanzous.com/iozm8fdvvrc
代码上传在这里了 你看一下 十分感谢

**Comment by Meowv** [comment]
Hosting 层没有依赖 EntityFrameworkCore。
```
 [DependsOn(
       typeof(AbpAspNetCoreMvcModule),
       typeof(AbpAutofacModule),
        typeof(ZhongZhiApiHttpApiModule),
        typeof(ZhongZhiApiEntityFrameworkCoreModule),
        typeof(ZhongZhiApiSwaggerModule)
    )]
    public class ZhongZhiApiHttpApiHostingModule : AbpModule
```

**Comment by yhxwyzm** [comment]
> Hosting 层没有依赖 EntityFrameworkCore。
> 
> ```
>  [DependsOn(
>        typeof(AbpAspNetCoreMvcModule),
>        typeof(AbpAutofacModule),
>         typeof(ZhongZhiApiHttpApiModule),
>         typeof(ZhongZhiApiEntityFrameworkCoreModule),
>         typeof(ZhongZhiApiSwaggerModule)
>     )]
>     public class ZhongZhiApiHttpApiHostingModule : AbpModule
> ```

十分感谢，没想到还是犯了这种低级错误
