### ISSUE TITLE
请问会添加搜索功能吗?

### ISSUE THREAD

**Issue by lxy0797** [Meowv/Blog#16]
这个博客项目很棒! 但是没有搜索这个功能好像少了什么? 搜索会在计划中吗?

**Comment by Meowv** [comment]
是的，目前没有搜索功能。如果想要写个搜索接口就行了，前端还需要设计下。
暂时没时间弄，有需要你可以自己试着写写？

**Comment by liuxinhh** [comment]
请问如何拓展 Abp.vnext自带的Identity模块, User 实体的外键呢？
例如我想在User 表中添加一个DeptId 部门的外键呢？
