### ISSUE TITLE
AuthorizeService中GenerateTokenAsync方法，调用Github获取用户信息接口问题

### ISSUE THREAD

**Issue by SinnoSong** [Meowv/Blog#21]
使用https://api.github.com/user?access_token={access_token} 尝试获取github用户信息时无法获取，提示Authorization是必须， 查看文档后发现现在不能用查询字符串形式获取github用户信息，而是需要在header中添加“Authorization”。类似："Authorization", $"token {access_token}"

**Comment by Meowv** [comment]
@sinnosong 
是的，之前版本已经不在更新修改了，可以看看最新的代码
https://github.com/Meowv/Blog/blob/main/src/Meowv.Blog.Application/Authorize/OAuth/Impl/OAuthGithubService.cs#L56
