### ISSUE TITLE
a very important async query issue!!!

### ISSUE THREAD

**Issue by wr404274848** [Meowv/Blog#24]
query=...from category in await _categoryRepository.GetListAsync()
                           join posts in await _postRepository.GetListAsync()
                           on category.Id equals posts.CategoryId
this code snip in your code is very expensive!!!
can change to this:
query=...from category in _categoryRepository
                           join posts in  _postRepository
                           on category.Id equals posts.CategoryId
await AsyncExecuter.ToListAsync(query);

**Comment by Meowv** [comment]
@wr404274848 
Thanks for the feedback, very good issue, I have time to fix it later.
