### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by iLayPark** [Meowv/Blog#3]
dotnet restore
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/root/Blog/MeowvBlog.sln]
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/root/Blog/MeowvBlog.sln]
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/root/Blog/MeowvBlog.sln]

**Comment by Meowv** [comment]
dotnet --info
确认是否有 .NET Core 2.2 SDK

**Comment by iLayPark** [comment]
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13


Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/


Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51


.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]


.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]


To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download





------------------ 原始邮件 ------------------
发件人: "阿星Plus"<notifications@github.com>; 
发送时间: 2019年8月20日(星期二) 中午1:03
收件人: "Meowv/Blog"<Blog@noreply.github.com>; 
抄送: "魏跃跃"<807190135@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Meowv/Blog] 编译错误 (#3)




dotnet --info
 确认是否有 .NET Core 2.2 SDK

**Comment by Meowv** [comment]
我是在Windows进行开发的，然后打包dll，发布至 centos 的

**Comment by iLayPark** [comment]
建议release附带上打包好的程序




------------------ 原始邮件 ------------------
发件人: "阿星Plus"<notifications@github.com>; 
发送时间: 2019年8月20日(星期二) 中午1:11
收件人: "Meowv/Blog"<Blog@noreply.github.com>; 
抄送: "魏跃跃"<807190135@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Meowv/Blog] 编译错误 (#3)




我是在Windows进行开发的，然后打包dll，发布至 centos 的
 
&mdash;

**Comment by iLayPark** [comment]
解决了
 export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
就可以了

**Comment by Meowv** [comment]
可能是没有启用ssl造成的，我在这里也看到了这个issue https://github.com/dotnet/corefx/issues/34066
