### ISSUE TITLE
老哥，前端的源码，可否发一波，学习学习

### ISSUE THREAD

**Issue by OxOld** [Meowv/Blog#7]
![image](https://user-images.githubusercontent.com/49990116/82167714-3c083d00-98ef-11ea-90f5-b00df19311cb.png)
![image](https://user-images.githubusercontent.com/49990116/82167718-3e6a9700-98ef-11ea-9b22-865e23191d62.png)

**Comment by Meowv** [comment]
源码也是参考LeaveIt的，或许你可以在我提交历史记录里面找一找，是有的。

![20200518130303](https://user-images.githubusercontent.com/13010050/82176004-12a7db00-9908-11ea-9e33-f6b943a1bc63.png)
