### ISSUE TITLE
缓存中出现数据更新时缓存如何更新的？

### ISSUE THREAD

**Issue by jonny-xhl** [Meowv/Blog#9]
## 说明
阿星 ，我翻阅了下源代码，几乎没什么问题，我这里有一个疑惑。

我看大多数的`Get` | `Query`请求都是走的缓存，我再看`Insert` |  `Update`的时候并没有更新缓存，那么这时候获取的数据就不是最新的？
是我那点没理解到吗？

**Comment by jonny-xhl** [comment]
## 举例
新增文章中往数据库中新增，这时并没有看到对缓存做处理！
![image](https://user-images.githubusercontent.com/29520329/83348310-f1120f00-a35d-11ea-9271-ca6f659b65b5.png)
然后分页读取文章（这时可能缓存中已经有数据，只是不是最新的），返回的还是未插入之间的数据！

![image](https://user-images.githubusercontent.com/29520329/83348338-2c144280-a35e-11ea-858d-f06688543a63.png)

**Comment by Meowv** [comment]
是的，在保存和更新操作的时候，目前还没有对缓存做任何操作。
这个我后面会加上的，如果你有需求，可以自己实现。

可以单独拿出来处理，写一些清除缓存的API，手动执行。也可以在当执行增删改操作成功后，清除缓存。
